language: go
sudo: required

go:
    - 1.9

go_import_path: github.com/clearlinux/mixer-tools

services:
    - docker

before_install:
    - docker build -t clearlinux .

script:
    - docker run clearlinux /bin/sh -c "cd /home/gopath/src/github.com/clearlinux/mixer-tools && make && make install && make lint && make check && make batcheck"
